In [1]:
from bs4 import BeautifulSoup as bs
import pandas as pd
import requests

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M"

full_page = requests.get(url).text
convert_to_bs4 = bs(full_page, 'html')
just_table = convert_to_bs4.find('table', {'class': 'wikitable'}).find_all('tr')

In [3]:
the_table = []

for i in just_table:
    td = i.find_all('td')
    the_table.append([i.text for i in td])
    
the_table

[[],
 ['M1A\n', 'Not assigned\n', 'Not assigned\n'],
 ['M2A\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3A\n', 'North York\n', 'Parkwoods\n'],
 ['M4A\n', 'North York\n', 'Victoria Village\n'],
 ['M5A\n', 'Downtown Toronto\n', 'Regent Park, Harbourfront\n'],
 ['M6A\n', 'North York\n', 'Lawrence Manor, Lawrence Heights\n'],
 ['M7A\n',
  'Downtown Toronto\n',
  "Queen's Park, Ontario Provincial Government\n"],
 ['M8A\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9A\n', 'Etobicoke\n', 'Islington Avenue, Humber Valley Village\n'],
 ['M1B\n', 'Scarborough\n', 'Malvern, Rouge\n'],
 ['M2B\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3B\n', 'North York\n', 'Don Mills\n'],
 ['M4B\n', 'East York\n', 'Parkview Hill, Woodbine Gardens\n'],
 ['M5B\n', 'Downtown Toronto\n', 'Garden District, Ryerson\n'],
 ['M6B\n', 'North York\n', 'Glencairn\n'],
 ['M7B\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8B\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9B\n',
  'Etobicoke\n',
  'West Deane Park, Princess Gardens, Martin Grove, Islington, Cloverdale\n'],
 ['M1C\n', 'Scarborough\n', 'Rouge Hill, Port Union, Highland Creek\n'],
 ['M2C\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3C\n', 'North York\n', 'Don Mills\n'],
 ['M4C\n', 'East York\n', 'Woodbine Heights\n'],
 ['M5C\n', 'Downtown Toronto\n', 'St. James Town\n'],
 ['M6C\n', 'York\n', 'Humewood-Cedarvale\n'],
 ['M7C\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8C\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9C\n',
  'Etobicoke\n',
  'Eringate, Bloordale Gardens, Old Burnhamthorpe, Markland Wood\n'],
 ['M1E\n', 'Scarborough\n', 'Guildwood, Morningside, West Hill\n'],
 ['M2E\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3E\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4E\n', 'East Toronto\n', 'The Beaches\n'],
 ['M5E\n', 'Downtown Toronto\n', 'Berczy Park\n'],
 ['M6E\n', 'York\n', 'Caledonia-Fairbanks\n'],
 ['M7E\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8E\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9E\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1G\n', 'Scarborough\n', 'Woburn\n'],
 ['M2G\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3G\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4G\n', 'East York\n', 'Leaside\n'],
 ['M5G\n', 'Downtown Toronto\n', 'Central Bay Street\n'],
 ['M6G\n', 'Downtown Toronto\n', 'Christie\n'],
 ['M7G\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8G\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9G\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1H\n', 'Scarborough\n', 'Cedarbrae\n'],
 ['M2H\n', 'North York\n', 'Hillcrest Village\n'],
 ['M3H\n',
  'North York\n',
  'Bathurst Manor, Wilson Heights, Downsview North\n'],
 ['M4H\n', 'East York\n', 'Thorncliffe Park\n'],
 ['M5H\n', 'Downtown Toronto\n', 'Richmond, Adelaide, King\n'],
 ['M6H\n', 'West Toronto\n', 'Dufferin, Dovercourt Village\n'],
 ['M7H\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8H\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9H\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1J\n', 'Scarborough\n', 'Scarborough Village\n'],
 ['M2J\n', 'North York\n', 'Fairview, Henry Farm, Oriole\n'],
 ['M3J\n', 'North York\n', 'Northwood Park, York University\n'],
 ['M4J\n', 'East York\n', 'East Toronto, Broadview North (Old East York)\n'],
 ['M5J\n',
  'Downtown Toronto\n',
  'Harbourfront East, Union Station, Toronto Islands\n'],
 ['M6J\n', 'West Toronto\n', 'Little Portugal, Trinity\n'],
 ['M7J\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8J\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9J\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1K\n', 'Scarborough\n', 'Kennedy Park, Ionview, East Birchmount Park\n'],
 ['M2K\n', 'North York\n', 'Bayview Village\n'],
 ['M3K\n', 'North York\n', 'Downsview\n'],
 ['M4K\n', 'East Toronto\n', 'The Danforth West, Riverdale\n'],
 ['M5K\n', 'Downtown Toronto\n', 'Toronto Dominion Centre, Design Exchange\n'],
 ['M6K\n', 'West Toronto\n', 'Brockton, Parkdale Village, Exhibition Place\n'],
 ['M7K\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8K\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9K\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1L\n', 'Scarborough\n', 'Golden Mile, Clairlea, Oakridge\n'],
 ['M2L\n', 'North York\n', 'York Mills, Silver Hills\n'],
 ['M3L\n', 'North York\n', 'Downsview\n'],
 ['M4L\n', 'East Toronto\n', 'India Bazaar, The Beaches West\n'],
 ['M5L\n', 'Downtown Toronto\n', 'Commerce Court, Victoria Hotel\n'],
 ['M6L\n', 'North York\n', 'North Park, Maple Leaf Park, Upwood Park\n'],
 ['M7L\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8L\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9L\n', 'North York\n', 'Humber Summit\n'],
 ['M1M\n',
  'Scarborough\n',
  'Cliffside, Cliffcrest, Scarborough Village West\n'],
 ['M2M\n', 'North York\n', 'Willowdale, Newtonbrook\n'],
 ['M3M\n', 'North York\n', 'Downsview\n'],
 ['M4M\n', 'East Toronto\n', 'Studio District\n'],
 ['M5M\n', 'North York\n', 'Bedford Park, Lawrence Manor East\n'],
 ['M6M\n', 'York\n', 'Del Ray, Mount Dennis, Keelsdale and Silverthorn\n'],
 ['M7M\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8M\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9M\n', 'North York\n', 'Humberlea, Emery\n'],
 ['M1N\n', 'Scarborough\n', 'Birch Cliff, Cliffside West\n'],
 ['M2N\n', 'North York\n', 'Willowdale, Willowdale East\n'],
 ['M3N\n', 'North York\n', 'Downsview\n'],
 ['M4N\n', 'Central Toronto\n', 'Lawrence Park\n'],
 ['M5N\n', 'Central Toronto\n', 'Roselawn\n'],
 ['M6N\n', 'York\n', 'Runnymede, The Junction North\n'],
 ['M7N\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8N\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9N\n', 'York\n', 'Weston\n'],
 ['M1P\n',
  'Scarborough\n',
  'Dorset Park, Wexford Heights, Scarborough Town Centre\n'],
 ['M2P\n', 'North York\n', 'York Mills West\n'],
 ['M3P\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4P\n', 'Central Toronto\n', 'Davisville North\n'],
 ['M5P\n',
  'Central Toronto\n',
  'Forest Hill North & West, Forest Hill Road Park\n'],
 ['M6P\n', 'West Toronto\n', 'High Park, The Junction South\n'],
 ['M7P\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8P\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9P\n', 'Etobicoke\n', 'Westmount\n'],
 ['M1R\n', 'Scarborough\n', 'Wexford, Maryvale\n'],
 ['M2R\n', 'North York\n', 'Willowdale, Willowdale West\n'],
 ['M3R\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4R\n', 'Central Toronto\n', 'North Toronto West,  Lawrence Park\n'],
 ['M5R\n', 'Central Toronto\n', 'The Annex, North Midtown, Yorkville\n'],
 ['M6R\n', 'West Toronto\n', 'Parkdale, Roncesvalles\n'],
 ['M7R\n', 'Mississauga\n', 'Canada Post Gateway Processing Centre\n'],
 ['M8R\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9R\n',
  'Etobicoke\n',
  'Kingsview Village, St. Phillips, Martin Grove Gardens, Richview Gardens\n'],
 ['M1S\n', 'Scarborough\n', 'Agincourt\n'],
 ['M2S\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3S\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4S\n', 'Central Toronto\n', 'Davisville\n'],
 ['M5S\n', 'Downtown Toronto\n', 'University of Toronto, Harbord\n'],
 ['M6S\n', 'West Toronto\n', 'Runnymede, Swansea\n'],
 ['M7S\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8S\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9S\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1T\n', 'Scarborough\n', "Clarks Corners, Tam O'Shanter, Sullivan\n"],
 ['M2T\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3T\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4T\n', 'Central Toronto\n', 'Moore Park, Summerhill East\n'],
 ['M5T\n',
  'Downtown Toronto\n',
  'Kensington Market, Chinatown, Grange Park\n'],
 ['M6T\n', 'Not assigned\n', 'Not assigned\n'],
 ['M7T\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8T\n', 'Not assigned\n', 'Not assigned\n'],
 ['M9T\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1V\n',
  'Scarborough\n',
  "Milliken, Agincourt North, Steeles East, L'Amoreaux East\n"],
 ['M2V\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3V\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4V\n',
  'Central Toronto\n',
  'Summerhill West, Rathnelly, South Hill, Forest Hill SE, Deer Park\n'],
 ['M5V\n',
  'Downtown Toronto\n',
  'CN Tower, King and Spadina, Railway Lands, Harbourfront West, Bathurst Quay, South Niagara, Island airport\n'],
 ['M6V\n', 'Not assigned\n', 'Not assigned\n'],
 ['M7V\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8V\n', 'Etobicoke\n', 'New Toronto, Mimico South, Humber Bay Shores\n'],
 ['M9V\n',
  'Etobicoke\n',
  'South Steeles, Silverstone, Humbergate, Jamestown, Mount Olive, Beaumond Heights, Thistletown, Albion Gardens\n'],
 ['M1W\n', 'Scarborough\n', "Steeles West, L'Amoreaux West\n"],
 ['M2W\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3W\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4W\n', 'Downtown Toronto\n', 'Rosedale\n'],
 ['M5W\n', 'Downtown Toronto\n', 'Stn A PO Boxes\n'],
 ['M6W\n', 'Not assigned\n', 'Not assigned\n'],
 ['M7W\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8W\n', 'Etobicoke\n', 'Alderwood, Long Branch\n'],
 ['M9W\n', 'Etobicoke\n', 'Northwest, West Humber - Clairville\n'],
 ['M1X\n', 'Scarborough\n', 'Upper Rouge\n'],
 ['M2X\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3X\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4X\n', 'Downtown Toronto\n', 'St. James Town, Cabbagetown\n'],
 ['M5X\n', 'Downtown Toronto\n', 'First Canadian Place, Underground city\n'],
 ['M6X\n', 'Not assigned\n', 'Not assigned\n'],
 ['M7X\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8X\n', 'Etobicoke\n', 'The Kingsway, Montgomery Road, Old Mill North\n'],
 ['M9X\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1Y\n', 'Not assigned\n', 'Not assigned\n'],
 ['M2Y\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3Y\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4Y\n', 'Downtown Toronto\n', 'Church and Wellesley\n'],
 ['M5Y\n', 'Not assigned\n', 'Not assigned\n'],
 ['M6Y\n', 'Not assigned\n', 'Not assigned\n'],
 ['M7Y\n',
  'East Toronto\n',
  'Business reply mail Processing Centre, South Central Letter Processing Plant Toronto\n'],
 ['M8Y\n',
  'Etobicoke\n',
  "Old Mill South, King's Mill Park, Sunnylea, Humber Bay, Mimico NE, The Queensway East, Royal York South East, Kingsway Park South East\n"],
 ['M9Y\n', 'Not assigned\n', 'Not assigned\n'],
 ['M1Z\n', 'Not assigned\n', 'Not assigned\n'],
 ['M2Z\n', 'Not assigned\n', 'Not assigned\n'],
 ['M3Z\n', 'Not assigned\n', 'Not assigned\n'],
 ['M4Z\n', 'Not assigned\n', 'Not assigned\n'],
 ['M5Z\n', 'Not assigned\n', 'Not assigned\n'],
 ['M6Z\n', 'Not assigned\n', 'Not assigned\n'],
 ['M7Z\n', 'Not assigned\n', 'Not assigned\n'],
 ['M8Z\n',
  'Etobicoke\n',
  'Mimico NW, The Queensway West, South of Bloor, Kingsway Park South West, Royal York South West\n'],
 ['M9Z\n', 'Not assigned\n', 'Not assigned\n']]

In [4]:
df = pd.DataFrame(the_table)

In [5]:
df

         0               1                                                  2
0     None            None                                               None
1    M1A\n  Not assigned\n                                     Not assigned\n
2    M2A\n  Not assigned\n                                     Not assigned\n
3    M3A\n    North York\n                                        Parkwoods\n
4    M4A\n    North York\n                                 Victoria Village\n
..     ...             ...                                                ...
176  M5Z\n  Not assigned\n                                     Not assigned\n
177  M6Z\n  Not assigned\n                                     Not assigned\n
178  M7Z\n  Not assigned\n                                     Not assigned\n
179  M8Z\n     Etobicoke\n  Mimico NW, The Queensway West, South of Bloor,...
180  M9Z\n  Not assigned\n                                     Not assigned\n

[181 rows x 3 columns]

In [6]:
df = df.dropna()

In [7]:
df.rename(columns={0:'PostalCode', 1: 'Borough', 2: 'Neighborhood'}, inplace=True)
df

/home/taz/.local/share/virtualenvs/Coursera_Capstone-5j-Ycuah/lib/python3.8/site-packages/pandas/core/frame.py:4125: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

,PostalCode,Borough,Neighborhood
1,M1A\n,Not assigned\n,Not assigned\n
2,M2A\n,Not assigned\n,Not assigned\n
3,M3A\n,North York\n,Parkwoods\n
4,M4A\n,North York\n,Victoria Village\n
5,M5A\n,Downtown Toronto\n,"Regent Park, Harbourfront\n"
...,...,...,...
176,M5Z\n,Not assigned\n,Not assigned\n
177,M6Z\n,Not assigned\n,Not assigned\n
178,M7Z\n,Not assigned\n,Not assigned\n
179,M8Z\n,Etobicoke\n,"Mimico NW, The Queensway West, South of Bloor,..."
180,M9Z\n,Not assigned\n,Not assigned\n

In [8]:
df['PostalCode'] = df['PostalCode'].str.strip('\n')
df['Borough'] =df['Borough'].str.strip('\n')
df['Neighborhood'] = df['Neighborhood'].str.strip('\n')

<ipython-input-8-e128d131e25b>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['PostalCode'] = df['PostalCode'].str.strip('\n')
<ipython-input-8-e128d131e25b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Borough'] =df['Borough'].str.strip('\n')
<ipython-input-8-e128d131e25b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Neighborhood'] = df['Neighborhood'].str.strip('\n')

In [9]:
df = df[df['Borough'] != 'Not assigned']
df

,PostalCode,Borough,Neighborhood
3,M3A,North York,Parkwoods
4,M4A,North York,Victoria Village
5,M5A,Downtown Toronto,"Regent Park, Harbourfront"
6,M6A,North York,"Lawrence Manor, Lawrence Heights"
7,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
161,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
166,M4Y,Downtown Toronto,Church and Wellesley
169,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
170,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
179,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

## Question two

In [10]:
geo_spatial = pd.read_csv('Geospatial_Coordinates.csv')

In [11]:
geo_spatial

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

In [12]:
df.reset_index(inplace=True, drop=True)

In [13]:
df

,PostalCode,Borough,Neighborhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

In [14]:
geo_spatial.rename(columns={'Postal Code': 'PostalCode'}, inplace=True)

In [15]:
df = df.merge(geo_spatial, on='PostalCode')

In [16]:
df

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M3A,North York,Parkwoods,43.753259,-79.329656
1,M4A,North York,Victoria Village,43.725882,-79.315572
2,M5A,Downtown Toronto,"Regent Park, Harbourfront",43.654260,-79.360636
3,M6A,North York,"Lawrence Manor, Lawrence Heights",43.718518,-79.464763
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government",43.662301,-79.389494
...,...,...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North",43.653654,-79.506944
99,M4Y,Downtown Toronto,Church and Wellesley,43.665860,-79.383160
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C...",43.662744,-79.321558
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu...",43.636258,-79.498509
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,...",43.628841,-79.520999

## Question 3

In [17]:
import numpy as np
import json
from pandas.io.json import json_normalize
from geopy.geocoders import Nominatim

import matplotlib.cm as cm
import matplotlib.colors as colors

from sklearn.cluster import KMeans

import folium

In [18]:
df['Borough'].unique()

array(['North York', 'Downtown Toronto', 'Etobicoke', 'Scarborough',
       'East York', 'York', 'East Toronto', 'West Toronto',
       'Central Toronto', 'Mississauga'], dtype=object)

In [19]:
def address_for_borough(borough_name):
    address = f'{borough_name}, Toronto, CA'
    geolocator = Nominatim(user_agent=f'{borough_name}, Toronto')
    location = geolocator.geocode(address)
    latitude = location.latitude
    longitude = location.longitude
    
    return latitude, longitude

In [20]:
york = address_for_borough('York')
york

(43.6896191, -79.479188)

In [21]:
york_df = df[df['Borough'] == 'York']

In [22]:
map_york = folium.Map(location=[york[0], york[1]], zoom_start=10)

for lat, lng, borough, neighborhood in zip(york_df['Latitude'], york_df['Longitude'], york_df['Borough'], york_df['Neighborhood']):
    label = '{}, {}'.format(neighborhood, borough)
    label = folium.Popup(label, parse_html=True)
    folium.CircleMarker(
        [lat, lng],
        radius=5,
        popup=label,
        color='blue',
        fill=True,
        fill_color='#3186cc',
        fill_opacity=0.7,
        parse_html=False).add_to(map_york)  
    
map_york

In [23]:
import os
CLIENT_ID = os.environ.get('CLIENT_ID')
CLIENT_SECRET = os.environ.get('CLIENT_SECRET')
VERSION = '20180605'

In [24]:
york_df.reset_index(inplace=True, drop = True)

In [25]:
york_df

,PostalCode,Borough,Neighborhood,Latitude,Longitude
0,M6C,York,Humewood-Cedarvale,43.693781,-79.428191
1,M6E,York,Caledonia-Fairbanks,43.689026,-79.453512
2,M6M,York,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013
3,M6N,York,"Runnymede, The Junction North",43.673185,-79.487262
4,M9N,York,Weston,43.706876,-79.518188

In [26]:
york_lat = york_df.loc[0, 'Latitude']
york_lon = york_df.loc[0, 'Longitude']

neighborhood_name = york_df.loc[0, 'Neighborhood']

print('Latitude and longitude values of {} are {}, {}.'.format(neighborhood_name, 
                                                               york_lat, 
                                                               york_lon))

Latitude and longitude values of Humewood-Cedarvale are 43.6937813, -79.42819140000002.

In [27]:
LIMIT = 100

radius = 500

url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
    CLIENT_ID, 
    CLIENT_SECRET, 
    VERSION, 
    york_lat, 
    york_lon, 
    radius, 
    LIMIT)

url

'https://api.foursquare.com/v2/venues/explore?&client_id=N40W0THAJDZYKLHLHWRDBU01LIMNXBMXZ03X5ZOGZSRVMLSR&client_secret=VZVTSYANXRZGSIHICOWNKPPR5C4QMVWIOGRB3CM0JVNTG151&v=20180605&ll=43.6937813,-79.42819140000002&radius=500&limit=100'

In [28]:
results = requests.get(url).json()
results

{'meta': {'code': 200, 'requestId': '5f2bd3820570a56adcdb409a'},
 'response': {'warning': {'text': "There aren't a lot of results near you. Try something more general, reset your filters, or expand the search area."},
  'headerLocation': 'Cedarvale',
  'headerFullLocation': 'Cedarvale, Toronto',
  'headerLocationGranularity': 'neighborhood',
  'totalResults': 3,
  'suggestedBounds': {'ne': {'lat': 43.6982813045, 'lng': -79.4219793104081},
   'sw': {'lat': 43.689281295499995, 'lng': -79.43440348959193}},
  'groups': [{'type': 'Recommended Places',
    'name': 'recommended',
    'items': [{'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4b0afc19f964a520212b23e3',
       'name': 'Cedarvale Park',
       'location': {'address': '100 glen cedar',
        'crossStreet': 'Strathearn',
        'lat': 43.692534923091934,
        'lng': -79.42870527613704,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.692534923091934,
          'lng': -79.42870527613704}],
        'distance': 144,
        'cc': 'CA',
        'city': 'Toronto',
        'state': 'ON',
        'country': 'Canada',
        'formattedAddress': ['100 glen cedar (Strathearn)',
         'Toronto ON',
         'Canada']},
       'categories': [{'id': '4bf58dd8d48988d15f941735',
         'name': 'Field',
         'pluralName': 'Fields',
         'shortName': 'Field',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/field_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4b0afc19f964a520212b23e3-0'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4c24abfcf7ced13aa425236d',
       'name': 'Cedarvale Ravine',
       'location': {'lat': 43.690188230007266,
        'lng': -79.42610580222994,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.690188230007266,
          'lng': -79.42610580222994}],
        'distance': 433,
        'cc': 'CA',
        'country': 'Canada',
        'formattedAddress': ['Canada']},
       'categories': [{'id': '4bf58dd8d48988d159941735',
         'name': 'Trail',
         'pluralName': 'Trails',
         'shortName': 'Trail',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/parks_outdoors/hikingtrail_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4c24abfcf7ced13aa425236d-1'},
     {'reasons': {'count': 0,
       'items': [{'summary': 'This spot is popular',
         'type': 'general',
         'reasonName': 'globalInteractionReason'}]},
      'venue': {'id': '4d1cd5f409546dcb10f1d538',
       'name': 'Phil White Arena',
       'location': {'address': '443 Arlington Avenue',
        'lat': 43.69130271699826,
        'lng': -79.43176051142332,
        'labeledLatLngs': [{'label': 'display',
          'lat': 43.69130271699826,
          'lng': -79.43176051142332}],
        'distance': 398,
        'cc': 'CA',
        'country': 'Canada',
        'formattedAddress': ['443 Arlington Avenue', 'Canada']},
       'categories': [{'id': '4bf58dd8d48988d185941735',
         'name': 'Hockey Arena',
         'pluralName': 'Hockey Arenas',
         'shortName': 'Hockey',
         'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/stadium_hockey_',
          'suffix': '.png'},
         'primary': True}],
       'photos': {'count': 0, 'groups': []}},
      'referralId': 'e-0-4d1cd5f409546dcb10f1d538-2'}]}]}}

In [29]:
def get_category_type(row):
    try:
        categories_list = row['categories']
    except:
        categories_list = row['venue.categories']
        
    if len(categories_list) == 0:
        return None
    else:
        return categories_list[0]['name']

In [30]:
venues = results['response']['groups'][0]['items']
    
nearby_venues = json_normalize(venues) # flatten JSON

# filter columns
filtered_columns = ['venue.name', 'venue.categories', 'venue.location.lat', 'venue.location.lng']
nearby_venues =nearby_venues.loc[:, filtered_columns]

# filter the category for each row
nearby_venues['venue.categories'] = nearby_venues.apply(get_category_type, axis=1)

# clean columns
nearby_venues.columns = [col.split(".")[-1] for col in nearby_venues.columns]

nearby_venues.head()

<ipython-input-30-561c05f0fdd1>:3: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  nearby_venues = json_normalize(venues) # flatten JSON

               name    categories        lat        lng
0    Cedarvale Park         Field  43.692535 -79.428705
1  Cedarvale Ravine         Trail  43.690188 -79.426106
2  Phil White Arena  Hockey Arena  43.691303 -79.431761

In [31]:
print('{} venues were returned by Foursquare.'.format(nearby_venues.shape[0]))

3 venues were returned by Foursquare.

In [32]:
def getNearbyVenues(names, latitudes, longitudes, radius=500):
    
    venues_list=[]
    for name, lat, lng in zip(names, latitudes, longitudes):
        print(name)
            
        # create the API request URL
        url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
            CLIENT_ID, 
            CLIENT_SECRET, 
            VERSION, 
            lat, 
            lng, 
            radius, 
            LIMIT)
            
        # make the GET request
        results = requests.get(url).json()["response"]['groups'][0]['items']
        
        # return only relevant information for each nearby venue
        venues_list.append([(
            name, 
            lat, 
            lng, 
            v['venue']['name'], 
            v['venue']['location']['lat'], 
            v['venue']['location']['lng'],  
            v['venue']['categories'][0]['name']) for v in results])

    nearby_venues = pd.DataFrame([item for venue_list in venues_list for item in venue_list])
    nearby_venues.columns = ['Neighborhood', 
                  'Neighborhood Latitude', 
                  'Neighborhood Longitude', 
                  'Venue', 
                  'Venue Latitude', 
                  'Venue Longitude', 
                  'Venue Category']
    
    return(nearby_venues)

In [33]:
york_venues = getNearbyVenues(names=york_df['Neighborhood'],
                                   latitudes=york_df['Latitude'],
                                   longitudes=york_df['Longitude']
                                  )

Humewood-Cedarvale
Caledonia-Fairbanks
Del Ray, Mount Dennis, Keelsdale and Silverthorn
Runnymede, The Junction North
Weston

In [34]:
print(york_venues.shape)
york_venues

(16, 7)

,Neighborhood,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Humewood-Cedarvale,43.693781,-79.428191,Cedarvale Park,43.692535,-79.428705,Field
1,Humewood-Cedarvale,43.693781,-79.428191,Cedarvale Ravine,43.690188,-79.426106,Trail
2,Humewood-Cedarvale,43.693781,-79.428191,Phil White Arena,43.691303,-79.431761,Hockey Arena
3,Caledonia-Fairbanks,43.689026,-79.453512,Nairn Park,43.690654,-79.456300,Park
4,Caledonia-Fairbanks,43.689026,-79.453512,Maximum Woman,43.690651,-79.456333,Women's Store
5,Caledonia-Fairbanks,43.689026,-79.453512,Landmark Restaurant,43.690400,-79.447702,Bar
6,Caledonia-Fairbanks,43.689026,-79.453512,Fairbanks Pool,43.691959,-79.448922,Pool
7,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013,Subway,43.690218,-79.474050,Sandwich Place
8,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013,Variety And Video,43.690105,-79.475143,Convenience Store
9,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013,Dollar Tree,43.690296,-79.474667,Discount Store
10,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013,Timothy's World Coffee,43.690072,-79.474599,Coffee Shop
11,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013,Z Bar & Grille,43.690673,-79.472764,Bar
12,"Runnymede, The Junction North",43.673185,-79.487262,Wonderfood,43.672352,-79.492571,Convenience Store
13,"Runnymede, The Junction North",43.673185,-79.487262,241 Pizza,43.672351,-79.492631,Pizza Place
14,"Runnymede, The Junction North",43.673185,-79.487262,Welcome Food Mart,43.669701,-79.483491,Grocery Store
15,"Runnymede, The Junction North",43.673185,-79.487262,Starving Artist,43.669860,-79.483110,Breakfast Spot

In [35]:
york_venues.groupby('Neighborhood').count()

,Neighborhood Latitude,Neighborhood Longitude,Venue,Venue Latitude,Venue Longitude,Venue Category
Neighborhood,,,,,,
Caledonia-Fairbanks,4,4,4,4,4,4
"Del Ray, Mount Dennis, Keelsdale and Silverthorn",5,5,5,5,5,5
Humewood-Cedarvale,3,3,3,3,3,3
"Runnymede, The Junction North",4,4,4,4,4,4

In [36]:
print('There are {} uniques categories.'.format(len(york_venues['Venue Category'].unique())))

There are 14 uniques categories.

In [37]:
# one hot encoding
york_onehot = pd.get_dummies(york_venues[['Venue Category']], prefix="", prefix_sep="")

# add neighborhood column back to dataframe
york_onehot['Neighborhood'] = york_venues['Neighborhood'] 

# move neighborhood column to the first column
fixed_columns = [york_onehot.columns[-1]] + list(york_onehot.columns[:-1])
york_onehot = york_onehot[fixed_columns]

york_onehot.head()

,Neighborhood,Bar,Breakfast Spot,Coffee Shop,Convenience Store,Discount Store,Field,Grocery Store,Hockey Arena,Park,Pizza Place,Pool,Sandwich Place,Trail,Women's Store
0,Humewood-Cedarvale,0,0,0,0,0,1,0,0,0,0,0,0,0,0
1,Humewood-Cedarvale,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,Humewood-Cedarvale,0,0,0,0,0,0,0,1,0,0,0,0,0,0
3,Caledonia-Fairbanks,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4,Caledonia-Fairbanks,0,0,0,0,0,0,0,0,0,0,0,0,0,1

In [38]:
york_onehot.shape

(16, 15)

In [39]:
york_grouped = york_onehot.groupby('Neighborhood').mean().reset_index()
york_grouped

,Neighborhood,Bar,Breakfast Spot,Coffee Shop,Convenience Store,Discount Store,Field,Grocery Store,Hockey Arena,Park,Pizza Place,Pool,Sandwich Place,Trail,Women's Store
0,Caledonia-Fairbanks,0.25,0.00,0.0,0.00,0.0,0.000000,0.00,0.000000,0.25,0.00,0.25,0.0,0.000000,0.25
1,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",0.20,0.00,0.2,0.20,0.2,0.000000,0.00,0.000000,0.00,0.00,0.00,0.2,0.000000,0.00
2,Humewood-Cedarvale,0.00,0.00,0.0,0.00,0.0,0.333333,0.00,0.333333,0.00,0.00,0.00,0.0,0.333333,0.00
3,"Runnymede, The Junction North",0.00,0.25,0.0,0.25,0.0,0.000000,0.25,0.000000,0.00,0.25,0.00,0.0,0.000000,0.00

In [40]:
york_grouped.shape

(4, 15)

In [41]:
num_top_venues = 5

for hood in york_grouped['Neighborhood']:
    print("----"+hood+"----")
    temp = york_grouped[york_grouped['Neighborhood'] == hood].T.reset_index()
    temp.columns = ['venue','freq']
    temp = temp.iloc[1:]
    temp['freq'] = temp['freq'].astype(float)
    temp = temp.round({'freq': 2})
    print(temp.sort_values('freq', ascending=False).reset_index(drop=True).head(num_top_venues))
    print('\n')

----Caledonia-Fairbanks----
            venue  freq
0             Bar  0.25
1            Park  0.25
2            Pool  0.25
3   Women's Store  0.25
4  Breakfast Spot  0.00


----Del Ray, Mount Dennis, Keelsdale and Silverthorn----
               venue  freq
0                Bar   0.2
1        Coffee Shop   0.2
2  Convenience Store   0.2
3     Discount Store   0.2
4     Sandwich Place   0.2


----Humewood-Cedarvale----
            venue  freq
0           Field  0.33
1    Hockey Arena  0.33
2           Trail  0.33
3             Bar  0.00
4  Breakfast Spot  0.00


----Runnymede, The Junction North----
               venue  freq
0     Breakfast Spot  0.25
1  Convenience Store  0.25
2      Grocery Store  0.25
3        Pizza Place  0.25
4                Bar  0.00

In [42]:
def return_most_common_venues(row, num_top_venues):
    row_categories = row.iloc[1:]
    row_categories_sorted = row_categories.sort_values(ascending=False)
    
    return row_categories_sorted.index.values[0:num_top_venues]

In [43]:
num_top_venues = 10

indicators = ['st', 'nd', 'rd']

# create columns according to number of top venues
columns = ['Neighborhood']
for ind in np.arange(num_top_venues):
    try:
        columns.append('{}{} Most Common Venue'.format(ind+1, indicators[ind]))
    except:
        columns.append('{}th Most Common Venue'.format(ind+1))

# create a new dataframe
neighborhoods_venues_sorted = pd.DataFrame(columns=columns)
neighborhoods_venues_sorted['Neighborhood'] = york_grouped['Neighborhood']

for ind in np.arange(york_grouped.shape[0]):
    neighborhoods_venues_sorted.iloc[ind, 1:] = return_most_common_venues(york_grouped.iloc[ind, :], num_top_venues)

neighborhoods_venues_sorted.head()

,Neighborhood,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,Caledonia-Fairbanks,Women's Store,Pool,Park,Bar,Trail,Sandwich Place,Pizza Place,Hockey Arena,Grocery Store,Field
1,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",Sandwich Place,Discount Store,Convenience Store,Coffee Shop,Bar,Women's Store,Trail,Pool,Pizza Place,Park
2,Humewood-Cedarvale,Trail,Hockey Arena,Field,Women's Store,Sandwich Place,Pool,Pizza Place,Park,Grocery Store,Discount Store
3,"Runnymede, The Junction North",Pizza Place,Grocery Store,Convenience Store,Breakfast Spot,Women's Store,Trail,Sandwich Place,Pool,Park,Hockey Arena

In [44]:
# set number of clusters
kclusters = 4

york_grouped_clustering = york_grouped.drop('Neighborhood', 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(york_grouped_clustering)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10]

array([0, 3, 1, 2], dtype=int32)

In [45]:
# add clustering labels
neighborhoods_venues_sorted.insert(0, 'Cluster Labels', kmeans.labels_)

york_merged = york_df

# merge toronto_grouped with toronto_data to add latitude/longitude for each neighborhood
york_merged = york_merged.join(neighborhoods_venues_sorted.set_index('Neighborhood'), on='Neighborhood')

york_merged.head() # check the last columns!

,PostalCode,Borough,Neighborhood,Latitude,Longitude,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,M6C,York,Humewood-Cedarvale,43.693781,-79.428191,1.0,Trail,Hockey Arena,Field,Women's Store,Sandwich Place,Pool,Pizza Place,Park,Grocery Store,Discount Store
1,M6E,York,Caledonia-Fairbanks,43.689026,-79.453512,0.0,Women's Store,Pool,Park,Bar,Trail,Sandwich Place,Pizza Place,Hockey Arena,Grocery Store,Field
2,M6M,York,"Del Ray, Mount Dennis, Keelsdale and Silverthorn",43.691116,-79.476013,3.0,Sandwich Place,Discount Store,Convenience Store,Coffee Shop,Bar,Women's Store,Trail,Pool,Pizza Place,Park
3,M6N,York,"Runnymede, The Junction North",43.673185,-79.487262,2.0,Pizza Place,Grocery Store,Convenience Store,Breakfast Spot,Women's Store,Trail,Sandwich Place,Pool,Park,Hockey Arena
4,M9N,York,Weston,43.706876,-79.518188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [59]:
# create map
map_clusters = folium.Map(location=[york[0], york[1]], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster in zip(york_merged['Latitude'], york_merged['Longitude'], york_merged['Neighborhood'], york_merged['Cluster Labels']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius=5,
        popup=label,
        color=rainbow,
        fill=True,
        fill_color=rainbow,
        fill_opacity=0.7).add_to(map_clusters)
       
map_clusters

In [47]:
color=rainbow
color

['#8000ff', '#2adddd', '#d4dd80', '#ff0000']

In [49]:
york_merged['Cluster Labels']

0    1.0
1    0.0
2    3.0
3    2.0
4    NaN
Name: Cluster Labels, dtype: float64

In [61]:
york_merged.loc[york_merged['Cluster Labels'] == 0, york_merged.columns[[1] + list(range(5, york_merged.shape[1]))]]

,Borough,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
1,York,0.0,Women's Store,Pool,Park,Bar,Trail,Sandwich Place,Pizza Place,Hockey Arena,Grocery Store,Field

In [62]:
york_merged.loc[york_merged['Cluster Labels'] == 1, york_merged.columns[[1] + list(range(5, york_merged.shape[1]))]]

,Borough,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
0,York,1.0,Trail,Hockey Arena,Field,Women's Store,Sandwich Place,Pool,Pizza Place,Park,Grocery Store,Discount Store

In [63]:
york_merged.loc[york_merged['Cluster Labels'] == 2, york_merged.columns[[1] + list(range(5, york_merged.shape[1]))]]

,Borough,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
3,York,2.0,Pizza Place,Grocery Store,Convenience Store,Breakfast Spot,Women's Store,Trail,Sandwich Place,Pool,Park,Hockey Arena

In [64]:
york_merged.loc[york_merged['Cluster Labels'] == 3, york_merged.columns[[1] + list(range(5, york_merged.shape[1]))]]

,Borough,Cluster Labels,1st Most Common Venue,2nd Most Common Venue,3rd Most Common Venue,4th Most Common Venue,5th Most Common Venue,6th Most Common Venue,7th Most Common Venue,8th Most Common Venue,9th Most Common Venue,10th Most Common Venue
2,York,3.0,Sandwich Place,Discount Store,Convenience Store,Coffee Shop,Bar,Women's Store,Trail,Pool,Pizza Place,Park

In [67]:
york_merged.loc[york_merged['Cluster Labels'] == 4, york_merged.columns[[1] + list(range(5, york_merged.shape[1]))]]

Empty DataFrame
Columns: [Borough, Cluster Labels, 1st Most Common Venue, 2nd Most Common Venue, 3rd Most Common Venue, 4th Most Common Venue, 5th Most Common Venue, 6th Most Common Venue, 7th Most Common Venue, 8th Most Common Venue, 9th Most Common Venue, 10th Most Common Venue]
Index: []